export enum NETWORK_TYPES {
  CORE_MAINNET = 'CORE_MAINNET',
  CORE_TESTNET = 'CORE_TESTNET',
  CORE_DEVNET = 'CORE_DEVNET',
  EVM_MAINNET = 'EVM_MAINNET',
  EVM_TESTNET = 'EVM_TESTNET',
  EVM_DEVNET = 'EVM_DEVNET',
  BTC_MAINNET = 'BTC_MAINNET',
  BTC_TESTNET = 'BTC_TESTNET',
  BTC_DEVNET = 'BTC_DEVNET',
}
